### ISSUE TITLE
[Android] 0x05d-Testing-Data-Storage [Shared Preferences]

### ISSUE THREAD

**Issue by david3107** [ing-bank/bdd-mobile-security-automation-framework#4]

**Comment by david3107** [comment]
Command: 

cat /data/data/ANDROID_PACKAGE/shared_prefs/*

**Comment by hopfenzapfen** [comment]
how about:
`grep -R "SENSITIVE INFORMATION" /data/data/ANDROID_PACKAGE/shared_prefs/*`
to me more consistent with #9

**Comment by david3107** [comment]
Also working. Would you make a pull request to change that?  Thanks
