### ISSUE TITLE
[Android] 0x05d-Testing-Data-Storage [SQLite Databases]

### ISSUE THREAD

**Issue by david3107** [ing-bank/bdd-mobile-security-automation-framework#5]

**Comment by david3107** [comment]
Use command

adb shell sqlite3 " + $path + $database + " .dump | grep #{plaintext} | wc -l

**Comment by hopfenzapfen** [comment]
Another command :wink: 
`grep "SENSITIVE_INFORMATION" /data/data/PACKAGE_NAME/databases/* `

* returns nothing if no match is found
* returns `Binary file /data/data/PACKAGE_NAME/databases/DATABASE_FILE matches` if a match is found

This also works without knowing the names of the databases in die `databases` directory.
